name: build
 
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0-beta.4 - 3.9.0

    - name: Install Sphinx
      run: python -m pip install Sphinx
 
    - name: Configure git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email mcsinyx@disroot.org
        git config user.name Nguyễn\ Gia\ Phong
        git remote set-url origin \
          https://token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git fetch origin gh-pages

    - name: Build and Deploy
      run: |
        tmpdir=$(mktemp --directory)
        make html
        mv --target-directory=$tmpdir doctrees html

        git switch gh-pages
        git rm -r doctrees html
        mv --target-directory=. $tmpdir/{doctrees,html}
        rm -r $tmpdir

        git add doctrees html
        git commit -m "Build at $(date --iso-8601=seconds)"
        git push origin gh-pages
