name: build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0-beta.4 - 3.9.0

    - name: Check out
      uses: actions/checkout@v2

    - name: Build Site
      run: |
        python -m pip install Sphinx
        make html

    - name: Configure git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email mcsinyx@disroot.org
        git config user.name Nguyễn\ Gia\ Phong
        git remote set-url origin \
          https://token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git fetch origin gh-pages

    - name: Deploy Site
      run: |
        git switch gh-pages
        git rm -r .
        shopt -s dotglob
        mv build/html/* .

        rm -r build
        git add .
        git commit -m "Build at $(date --iso-8601=seconds)"
        git push origin gh-pages
